[[iODBC]]
arch = "aarch64"
git-tree-sha1 = "56047b38d9c9cb6683aac46c4aed471029cffb40"
os = "macos"

    [[iODBC.download]]
    sha256 = "dec3970aec89b7fb90b0dc8e2688891401ff9d84b1d3ee9f724bc46616bc9c2f"
    url = "https://github.com/JuliaBinaryWrappers/iODBC_jll.jl/releases/download/iODBC-v3.52.15+0/iODBC.v3.52.15.aarch64-apple-darwin.tar.gz"
[[iODBC]]
arch = "aarch64"
git-tree-sha1 = "81738bc1e8af0b8de39a01c3d2af4f5bdf49c6ec"
libc = "glibc"
os = "linux"

    [[iODBC.download]]
    sha256 = "3d5eca8b268210a626de25b1e64a101db25db8fda20a39c96c873c6adeeebf01"
    url = "https://github.com/JuliaBinaryWrappers/iODBC_jll.jl/releases/download/iODBC-v3.52.15+0/iODBC.v3.52.15.aarch64-linux-gnu.tar.gz"
[[iODBC]]
arch = "aarch64"
git-tree-sha1 = "287f0ca7d74226c67d1a9dd27a71b104234a6723"
libc = "musl"
os = "linux"

    [[iODBC.download]]
    sha256 = "a160dc9248754d39bff4a1dfc2196c0cfd33a45ef9bfdfbedd25f5eaa6f73d41"
    url = "https://github.com/JuliaBinaryWrappers/iODBC_jll.jl/releases/download/iODBC-v3.52.15+0/iODBC.v3.52.15.aarch64-linux-musl.tar.gz"
[[iODBC]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "053f85769553f76fc66da68a8c0d77d653f30fbd"
libc = "glibc"
os = "linux"

    [[iODBC.download]]
    sha256 = "f3d89cc3e9da1e7ea3682bb4fb9aa5c2db4a3cc9dd377b7487d044f63783cfc4"
    url = "https://github.com/JuliaBinaryWrappers/iODBC_jll.jl/releases/download/iODBC-v3.52.15+0/iODBC.v3.52.15.armv6l-linux-gnueabihf.tar.gz"
[[iODBC]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3fd016fcc0df02a1664a4a0f7887f8237387f0d5"
libc = "musl"
os = "linux"

    [[iODBC.download]]
    sha256 = "33b8184082cac950b270f5697cc2e045d1f77eeb886812d66a0314ab04b752d0"
    url = "https://github.com/JuliaBinaryWrappers/iODBC_jll.jl/releases/download/iODBC-v3.52.15+0/iODBC.v3.52.15.armv6l-linux-musleabihf.tar.gz"
[[iODBC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0f27807e271cbc2ead94a8a8088fef489ed2aaae"
libc = "glibc"
os = "linux"

    [[iODBC.download]]
    sha256 = "1ca9f167bf64333ef01136f98c7c993b8cc3669f5e43f907837415af20cf2df5"
    url = "https://github.com/JuliaBinaryWrappers/iODBC_jll.jl/releases/download/iODBC-v3.52.15+0/iODBC.v3.52.15.armv7l-linux-gnueabihf.tar.gz"
[[iODBC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9c0f570cde707dc4efd5629f8b940e0211ba7f7d"
libc = "musl"
os = "linux"

    [[iODBC.download]]
    sha256 = "60d72184fd57a539162989dccfd4e87246b31624af51c4263075bb6e9dd05684"
    url = "https://github.com/JuliaBinaryWrappers/iODBC_jll.jl/releases/download/iODBC-v3.52.15+0/iODBC.v3.52.15.armv7l-linux-musleabihf.tar.gz"
[[iODBC]]
arch = "i686"
git-tree-sha1 = "5a9f14b4b82b0fbe7349e4c31fbc1a2fdeecdea7"
libc = "glibc"
os = "linux"

    [[iODBC.download]]
    sha256 = "5b4a10ac0dfc0ee5324fdfbfd15146f7a64e18c1eb129ddc3157a14f1b0365ea"
    url = "https://github.com/JuliaBinaryWrappers/iODBC_jll.jl/releases/download/iODBC-v3.52.15+0/iODBC.v3.52.15.i686-linux-gnu.tar.gz"
[[iODBC]]
arch = "i686"
git-tree-sha1 = "5768dfda4e5853f28a7fbb464f39cf8f35bacdc5"
libc = "musl"
os = "linux"

    [[iODBC.download]]
    sha256 = "50268df7adbf00c57e2244653ca856361241e8e87adda1f0f905e1d8baf27d40"
    url = "https://github.com/JuliaBinaryWrappers/iODBC_jll.jl/releases/download/iODBC-v3.52.15+0/iODBC.v3.52.15.i686-linux-musl.tar.gz"
[[iODBC]]
arch = "powerpc64le"
git-tree-sha1 = "ad6242805c38ef66150120fba3e91a3ed5907419"
libc = "glibc"
os = "linux"

    [[iODBC.download]]
    sha256 = "3fbe66f4d310d61db57081b2c2b95305402ca314d09f52dfff60ecb5957fdefb"
    url = "https://github.com/JuliaBinaryWrappers/iODBC_jll.jl/releases/download/iODBC-v3.52.15+0/iODBC.v3.52.15.powerpc64le-linux-gnu.tar.gz"
[[iODBC]]
arch = "x86_64"
git-tree-sha1 = "ea58b8500e2b57925720f9b8c1497bbd54b26d91"
os = "macos"

    [[iODBC.download]]
    sha256 = "6bcda461925adafaf454244b681f6469cc406bb65da72b01f9280226c959252c"
    url = "https://github.com/JuliaBinaryWrappers/iODBC_jll.jl/releases/download/iODBC-v3.52.15+0/iODBC.v3.52.15.x86_64-apple-darwin.tar.gz"
[[iODBC]]
arch = "x86_64"
git-tree-sha1 = "b7cbaa05336ba8c43342b290a4448dfcba79c287"
libc = "glibc"
os = "linux"

    [[iODBC.download]]
    sha256 = "98908eb48a3690e7cfce22ebbef45373ba928d9c9ccb24b7319def29ebb40f5e"
    url = "https://github.com/JuliaBinaryWrappers/iODBC_jll.jl/releases/download/iODBC-v3.52.15+0/iODBC.v3.52.15.x86_64-linux-gnu.tar.gz"
[[iODBC]]
arch = "x86_64"
git-tree-sha1 = "1cd75aea3d78f4833e3b4db84714281085862d2b"
libc = "musl"
os = "linux"

    [[iODBC.download]]
    sha256 = "8bd5f2943f8496d7919cc242c821e4a6225f6d5b70d5998eb6e43872800ce816"
    url = "https://github.com/JuliaBinaryWrappers/iODBC_jll.jl/releases/download/iODBC-v3.52.15+0/iODBC.v3.52.15.x86_64-linux-musl.tar.gz"
[[iODBC]]
arch = "x86_64"
git-tree-sha1 = "bf329af15aae23ac1ba0cc98d5dca578a0ac26b9"
os = "freebsd"

    [[iODBC.download]]
    sha256 = "a36d618319cad68c881cbc07557f4b421ab0fa6e49427ee283bad9e529545cfc"
    url = "https://github.com/JuliaBinaryWrappers/iODBC_jll.jl/releases/download/iODBC-v3.52.15+0/iODBC.v3.52.15.x86_64-unknown-freebsd.tar.gz"
