# Autogenerated wrapper script for iODBC_jll for x86_64-apple-darwin
export iodbctest, iodbctestw, libiodbc, libiodbcinst

JLLWrappers.@generate_wrapper_header("iODBC")
JLLWrappers.@declare_library_product(libiodbc, "@rpath/libiodbc.2.dylib")
JLLWrappers.@declare_library_product(libiodbcinst, "@rpath/libiodbcinst.2.dylib")
JLLWrappers.@declare_executable_product(iodbctest)
JLLWrappers.@declare_executable_product(iodbctestw)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libiodbc,
        "lib/libiodbc.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libiodbcinst,
        "lib/libiodbcinst.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        iodbctest,
        "bin/iodbctest",
    )

    JLLWrappers.@init_executable_product(
        iodbctestw,
        "bin/iodbctestw",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
